export const GET_RESOURCES = 'COM_AWORKINGAPP_GET_RESOURCES';

export const GET_RESOURCE = 'COM_AWORKINGAPP_GET_RESOURCE';

export const POST_RESOURCE = 'COM_AWORKINGAPP_POST_RESOURCE';

export const PUT_RESOURCE = 'COM_AWORKINGAPP_PUT_RESOURCE';

export const DELETE_RESOURCE = 'COM_AWORKINGAPP_DELETE_RESOURCE';

export const CUSTOM_ACTION_RESOURCE = 'COM_AWORKINGAPP_CUSTOM_ACTION_RESOURCE';
export const CUSTOM_ACTION_RESOURCES = 'COM_AWORKINGAPP_CUSTOM_ACTION_RESOURCES';

export const REQUEST_SUCCESS = '@@/COM_AWORKINGAPP/REQUEST_SUCCESS';
export const REQUEST_ERROR = '@@/COM_AWORKINGAPP/REQUEST_ERROR';

export const METHODS = {
    GET: 'get',
    POST: 'post',
    PUT: 'put',
    DELETE: 'delete'
};
