export const GET_RESOURCES = 'REDUX_REST_RESOURCE_GET_RESOURCES';

export const GET_RESOURCE = 'REDUX_REST_RESOURCE_GET_RESOURCE';

export const POST_RESOURCE = 'REDUX_REST_RESOURCE_POST_RESOURCE';

export const PUT_RESOURCE = 'REDUX_REST_RESOURCE_PUT_RESOURCE';

export const DELETE_RESOURCE = 'REDUX_REST_RESOURCE_DELETE_RESOURCE';

export const CUSTOM_ACTION_RESOURCE = 'REDUX_REST_RESOURCE_CUSTOM_ACTION_RESOURCE';
export const CUSTOM_ACTION_RESOURCES = 'REDUX_REST_RESOURCE_CUSTOM_ACTION_RESOURCES';

export const REQUEST_SUCCESS = '@@/REDUX_REST_RESOURCE/REQUEST_SUCCESS';
export const REQUEST_ERROR = '@@/REDUX_REST_RESOURCE/REQUEST_ERROR';

export const RUNTIME_ERROR = '@@/REDUX_REST_RESOURCE/RUNTIME_ERROR';

export const METHODS = {
    GET: 'get',
    POST: 'post',
    PUT: 'put',
    DELETE: 'delete'
};
